### ISSUE TITLE
`toStringWithSourceMap` behaves incorrectly if `SourceNode`s source is `null` or is an empty string

### ISSUE THREAD

**Issue by Mingun** [mozilla/source-map#444]
When `source` set to `null`, mapping does not generated.
When `source` set to empty string there is an error during mapping calculation (not during `SourceNode` creation as expected if empty string is forbidden).

This code snippet demonstrates both problems: https://runkit.com/embed/47lduu6k2173

Source code of the snippet:
```js
let SourceNode = require('source-map').SourceNode;

function test(source) {
  let node = new SourceNode(
    null,
    null,
    source,
    [
      'prefix',
      new SourceNode(1, 0, source, 'code'),
      'suffix',
    ]
  );
  let { code, map } = node.toStringWithSourceMap();
  console.log(map.toJSON(), code);
}
test("source");// OK
test(null);    // Empty mapping
test("");      // Exception
```

**Comment by Mingun** [comment]
At least, an error should be thrown instead of silent incorrect work. At most, the problem should be fixed to allow any source

**Comment by hildjj** [comment]
(sorry, just noticed which repo this was on.  I agree with Mingun that this is still an issue)

**Comment by ochameau** [comment]
> At least, an error should be thrown in the `SourceNode` constructor instead of silent incorrect work, if it is desired behavior.
> At most, the problem should be fixed to allow any source

It isn't crystal clear what would be the expectation when passing a null source.

We might convert any falsy `source` value in `SourceNode` constructor to become `null`.
So that we no longer throw in `_validateMapping`.
But then... what would be the expected mapping?

Today when passing null, we generate:
> // {version: 3, sources: [], names: [], mappings: ""}
Would you expect the following instead?
> // {version: 3, sources: [], names: [], mappings: "MAAA,I"}
or
> // {version: 3, sources: [null], names: [], mappings: "MAAA,I"}

v3 specification isn't saying much about the expected content of `sources` array.

**Comment by Mingun** [comment]
From consistency point of view I think that
```js
{version: 3, sources: [null], names: [], mappings: "MAAA,I"}
```
would the best solution for `null`, and
```js
{version: 3, sources: [""], names: [], mappings: "MAAA,I"}
```
would the best solution for `""`.

**Comment by Mingun** [comment]
No. I found this issue when I write tests for peggy in peggyjs/peggy#163. I don't think, that using `null`, `undefined` or empty string would be really used by someone, but I think it is better to provide consistent behavior in all cases.

As I said early, I will be satisfied with support in some form, that will provide consistent behavior, or throwing out an exception from `SourceNode` constructor is you decide that some inputs should not be used.
